#!/bin/bash

set -e

#########################################################
#
# Platform: NCI Gadi HPC
#
# Author: Tracy Chew
# tracy.chew@sydney.edu.au
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub (or co-authorship, where appropriate).
#
# Suggested acknowledgement:
# The authors acknowledge the scientific and technical assistance
# <or e.g. bioinformatics assistance of <PERSON>> of Sydney Informatics
# Hub and resources and services from the National Computational
# Infrastructure (NCI), which is supported by the Australian Government
# with access facilitated by the University of Sydney.
#
#########################################################

#PBS -P <project>
#PBS -l walltime=10:00:00
#PBS -l ncpus=48
#PBS -l mem=190GB
#PBS -W umask=022
#PBS -q normal
#PBS -l wd
#PBS -lstorage=scratch/<project>
#PBS -N diamond_makedb

module load diamond/2.0.11

FASTA=nr.gz
out=diamond_ncbi

# Doesn't seem to work with gzipped files, unzip first

gunzip ${FASTA}

diamond makedb \
	-p ${NCPUS} \
	--in ./nr \
	--taxonmap prot.accession2taxid.FULL.gz \
	--taxonnodes nodes.dmp \
	--taxonnames names.dmp \
	--db ./nr.dmnd \
	--out ${out}
