#!/bin/bash

#########################################################
#
# Platform: NCI Gadi HPC
# Description: see https://github.com/Sydney-Informatics-Hub/Shotgun-Metagenomics-Analysis
#
# Author/s: Tracy Chew
# tracy.chew@sydney.edu.au
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub (or co-authorship, where appropriate).
#
# Suggested acknowledgement:
# The authors acknowledge the scientific and technical assistance
# <or e.g. bioinformatics assistance of <PERSON>> of Sydney Informatics
# Hub and resources and services from the National Computational
# Infrastructure (NCI), which is supported by the Australian Government
# with access facilitated by the University of Sydney.
#
#########################################################

#PBS -P <project>
#PBS -N get-NR
#PBS -l walltime=10:00:00
#PBS -l ncpus=1
#PBS -l mem=8GB
#PBS -W umask=022
#PBS -q copyq
#PBS -l wd
#PBS -o ./Logs/download_NR.o
#PBS -e ./Logs/download_NR.e
#PBS -l storage=scratch/<project>

set -e

database_dir=./NCBI_NR

mkdir -p $database_dir
cd $database_dir

echo Downloading nr.gz
wget https://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/nr.gz

echo Downloading nr.gz.md5
wget https://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/nr.gz.md5

echo Downloading prot.accession2taxid.FULL.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.FULL.gz

echo Downloading taxdmp.zip
wget ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdmp.zip

echo Checking md5sums for nr.gz
md5sum -c nr.gz.md5

