#!/bin/bash

#########################################################
#
# Platform: NCI Gadi HPC
# Description: see https://github.com/Sydney-Informatics-Hub/Shotgun-Metagenomics-Analysis
#
# Author/s: Cali Willet
# cali.willet@sydney.edu.au
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub (or co-authorship, where appropriate).
#
# Suggested acknowledgement:
# The authors acknowledge the scientific and technical assistance
# <or e.g. bioinformatics assistance of <PERSON>> of Sydney Informatics
# Hub and resources and services from the National Computational
# Infrastructure (NCI), which is supported by the Australian Government
# with access facilitated by the University of Sydney.
#
#########################################################

#PBS -P <project>
#PBS -N IS
#PBS -l walltime=24:00:00
#PBS -l ncpus=12
#PBS -l mem=48GB
#PBS -q normal
#PBS -W umask=022 
#PBS -l wd 
#PBS -l storage=scratch/<project>
 
module load openmpi/4.1.0
module load nci-parallel/1.0.0a
module load prokka/1.14.5 
module load java/jdk-8.40
module load parallel/20191022

contigs=./Assembly/${sample}/${sample}.filteredContigs.fa
db=./ISfinder-sequences/IS.faa

prokka --cpus ${NCPUS} \
	--outdir ./Insertion_sequences/${sample} \
	--force \
	--prefix ${sample} \
	--addgenes \
	--kingdom Bacteria \
	--proteins ${db} \
	${contigs}

