#!/bin/bash

#########################################################
#
# Platform: NCI Gadi HPC
# Description: see https://github.com/Sydney-Informatics-Hub/Shotgun-Metagenomics-Analysis
#
# Author/s: Cali Willet
# cali.willet@sydney.edu.au
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub (or co-authorship, where appropriate).
#
# Suggested acknowledgement:
# The authors acknowledge the scientific and technical assistance
# <or e.g. bioinformatics assistance of <PERSON>> of Sydney Informatics
# Hub and resources and services from the National Computational
# Infrastructure (NCI), which is supported by the Australian Government
# with access facilitated by the University of Sydney.
#
#########################################################

#PBS -P <project>
#PBS -N k2-db-build
#PBS -l walltime=04:00:00
#PBS -l ncpus=48
#PBS -l mem=190GB
#PBS -q normal
#PBS -W umask=022
#PBS -l wd
#PBS -o ./Logs/kraken2_db_build.o
#PBS -e ./Logs/kraken2_db_build.e
#PBS -l storage=scratch/<project>

module load kraken2/2.0.8-beta
unset OMP_NUM_THREADS #from github.com/DerrickWood/kraken2/issues/348#issuecomment-743106099

echo Building kraken2 database $dbname

kraken2-build \
	--build \
	--threads $NCPUS \
	--db $dbname

