#!/bin/bash

set -e

#########################################################
#
# Platform: NCI Gadi HPC
#
# Author: Tracy Chew
# tracy.chew@sydney.edu.au
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub (or co-authorship, where appropriate).
#
# Suggested acknowledgement:
# The authors acknowledge the scientific and technical assistance
# <or e.g. bioinformatics assistance of <PERSON>> of Sydney Informatics
# Hub and resources and services from the National Computational
# Infrastructure (NCI), which is supported by the Australian Government
# with access facilitated by the University of Sydney.
#
#########################################################

#PBS -P <project>
#PBS -l walltime=02:00:00
#PBS -l ncpus=1
#PBS -l mem=4GB
#PBS -q normal
#PBS -W umask=022
#PBS -l wd
#PBS -lstorage=scratch/<project>
#PBS -l jobfs=400GB
#PBS -o ./Logs/match_ARGs_to_diamond_cds.o
#PBS -e ./Logs/match_ARGs_to_diamond_cds.e

set -e

perl ./match_ARGs_to_diamond_cds.pl
